title: My first repository
description: This is my first repository setting up and initializing GitHub
template:
  repo: my-first-repository-template
  name: my-first-repository
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
